In [1]:
import numpy as np

In [8]:
# a. Create a null vector of size 10 but the fifth value which is 1
a = np.zeros(10)
a[5] = 1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [10]:
# b. Create a vector with values ranging from 10 to 49
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
# c. Reverse a vector (first element becomes last)
c = b[::-1]
c

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [16]:
# d. Create a 3x3 matrix with values ranging from 0 to 8
d = np.arange(9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# e. Find indices of non-zero elements from [1,2,0,0,4,0]
e = [1,2,0,0,4,0]
print(np.nonzero(e))

(array([0, 1, 4]),)


In [75]:
# f. Create a random vector of size 30 and find the mean value
f = np.random.randint(30,size = 30)
np.mean(f)

np.float64(13.9)

In [60]:
# g. Create a 2d array with 1 on the border and 0 inside
np.random.seed(0)
g = np.random.randint(25, size=(5, 5))
g[1:-1,1:-1] = 0
g

array([[12, 15, 21,  0,  3],
       [ 3,  0,  0,  0, 21],
       [18,  0,  0,  0, 24],
       [24,  0,  0,  0,  7],
       [23, 14, 24, 17,  5]], dtype=int32)

In [71]:
# h. Create a 8x8 matrix and fill it with a checkerboard pattern
h = np.zeros((8,8))
h[::2,1::2] = 1
h[1::2,::2] = 1
h

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [73]:
# i. Create a checkerboard 8x8 matrix using the tile function
i = np.tile([[0,1],[1,0]],(4,4))
i

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [78]:
# j. Given a 1D array, negate all elements which are between 3 and 8, in place
np.random.seed(0)
j = np.random.randint(10,size=10)
j[(j>3) & (j<8)] *= -1
j

array([-5,  0,  3,  3, -7,  9,  3, -5,  2, -4], dtype=int32)

In [81]:
# k. Create a random vector of size 10 and sort it
np.random.seed(0)
k = np.random.randint(10,size=10)
k.sort()
k

array([0, 2, 3, 3, 3, 4, 5, 5, 7, 9], dtype=int32)

In [85]:
# l. Consider two random array A anb B, check if they are equal
A = np.random.randint(10,size =(2,2))
B = np.random.randint(10,size =(2,2))
equel = np.array_equal(A,B)
equel

False

In [ ]:
# m. How to calculate the square of every number in an array in place (without creating temporaries)?


In [ ]:
# n. How to get the diagonal of a dot product?
